meta_product_name: "Offgrid"
meta_title: "Offgrid - Go out exploring, get home safe"
meta_description: "Plan your next hike in one place and immerse yourself in nature knowing your safety is accounted for."
meta_image: "offgrid_logo_big.png" # should exist in `app/assets/images/`
